### ISSUE TITLE
Down migration for blanket logs

### ISSUE THREAD

**Issue by iKlsR** [AhmadWaleed/laravel-blanket#11]
It's not uncommon to run `migrate:refresh` when developing, having blanket not have a down command will break this flow.

**Comment by AhmadWaleed** [comment]
You can publish blanket migrations by running `php artisan vendor:publish --provider="Ahmadwaleed\Blanket\BlanketServiceProvider" --tag="blanket-migrations"` then migrate:fresh will also apply on blanket migrations.

**Comment by iKlsR** [comment]
<strike>I did, it only had the [up](https://github.com/AhmadWaleed/laravel-blanket/blob/main/database/migrations/create_blanket_logs_table.php#L9) however?</strike> Nevermind, `fresh`, not `refresh`.
