### ISSUE TITLE
Blank page on accessing /blanket

### ISSUE THREAD

**Issue by milanchheda** [AhmadWaleed/laravel-blanket#12]
Hey,

I am getting the following error upon accessing `/blanket` route: 

![image](https://user-images.githubusercontent.com/1329515/153553114-8599d852-b05b-4b84-b520-32c30a29d39f.png)

Does it depend on Vue or anything? 

**Note:** I don't have Vue installed.

**Comment by vicenterusso** [comment]
related to this fix: https://github.com/AhmadWaleed/laravel-blanket/pull/16
