### ISSUE TITLE
Add built in prune command

### ISSUE THREAD

**Issue by iKlsR** [AhmadWaleed/laravel-blanket#3]
Most packages like this come with some built in way to setup a pruning schedule. Would be nice to have one included as well, currently I'm just deleting older than a week records in a custom job.

`$schedule->command('blanket:prune')->daily();` would be nice! Thanks, very useful package. https://github.com/laravel/telescope/search?q=prune

**Comment by AhmadWaleed** [comment]
I think its a good idea, I will add the prunable support to Blanket model.

**Comment by AhmadWaleed** [comment]
Added prunable model support please update to [v1.1.0](https://github.com/AhmadWaleed/laravel-blanket/releases/tag/v1.1.0)
